# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
enable-beta-ecosystems: true # Julia ecosystem
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "crate-ci/typos"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
      - "/test"
      - "/benchmarks/AdaptiveSDE"
      - "/benchmarks/AstroChem"
      - "/benchmarks/AutomaticDifferentiation"
      - "/benchmarks/AutomaticDifferentiationSparse"
      - "/benchmarks/BayesianInference"
      - "/benchmarks/Bio"
      - "/benchmarks/ComplicatedPDE"
      - "/benchmarks/DAE"
      - "/benchmarks/DynamicalODE"
      - "/benchmarks/GlobalOptimization"
      - "/benchmarks/HybridJumps"
      - "/benchmarks/IntervalNonlinearProblem"
      - "/benchmarks/Jumps"
      - "/benchmarks/LinearSolve"
      - "/benchmarks/MethodOfLinesPDE"
      - "/benchmarks/ModelingToolkit"
      - "/benchmarks/MultiLanguage"
      - "/benchmarks/NBodySimulator"
      - "/benchmarks/NonlinearProblem"
      - "/benchmarks/NonStiffBVP"
      - "/benchmarks/NonStiffDDE"
      - "/benchmarks/NonStiffODE"
      - "/benchmarks/NonStiffSDE"
      - "/benchmarks/Optimization"
      - "/benchmarks/OptimizationCUTEst"
      - "/benchmarks/OptimizationFrameworks"
      - "/benchmarks/ParameterEstimation"
      - "/benchmarks/PINNErrorsVsTime"
      - "/benchmarks/PINNOptimizers"
      - "/benchmarks/SimpleHandwrittenPDE"
      - "/benchmarks/StiffBVP"
      - "/benchmarks/StiffDDE"
      - "/benchmarks/StiffODE"
      - "/benchmarks/StiffSDE"
      - "/benchmarks/Surrogates"
      - "/benchmarks/Symbolics"
      - "/benchmarks/Testing"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 40
    groups:
      all-julia-packages:
        patterns:
          - "*"
