[default.extend-words]
ba = "ba"
ded = "ded"
Missings = "Missings"
daa = "daa"
Pase = "Pase"
ede = "ede"
afe = "afe"
aded = "aded"
strat = "strat"
myu = "myu"
ND = "ND"
nd = "nd"
ned = "ned"
sitl = "sitl"
IIF = "IIF"
opf = "opf"
OPF = "OPF"
MEK = "MEK"
ein = "ein"
pn = "pn"
Pn = "Pn"
dbe = "dbe"

[files]
extend-exclude = ["benchmarks/OptimizationFrameworks/opf_data/"]
