agents:
  queue: "juliaecosystem"
  sandbox_capable: true

steps:
  - label: ":runner: Dynamically launch run_benchmark.yml (CPU)"
    branches: "!gh-pages"
    env:
      BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET: ${BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET?}
    depends_on:
    plugins:
      - staticfloat/forerunner#v1:
          # This will create one job per project (excluding GPU benchmarks)
          # Note: Using extglob !(GPU) pattern since forerunner doesn't support 'ignore'
          watch:
            - benchmarks/!(GPU)/**/*.jmd
            - benchmarks/!(GPU)/**/*.toml
          path_processor: .buildkite/path_processors/project-coalescing
          target: .buildkite/run_benchmark.yml
          target_type: template

  - label: ":runner: :gpu: Dynamically launch run_gpu_benchmark.yml (GPU)"
    branches: "!gh-pages"
    env:
      BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET: ${BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET?}
    depends_on:
    plugins:
      - staticfloat/forerunner#v1:
          # This will create one job per GPU benchmark
          watch:
            - benchmarks/GPU/*.jmd
            - benchmarks/GPU/*.toml
            - benchmarks/GPU/**/*.jmd
            - benchmarks/GPU/**/*.toml
          path_processor: .buildkite/path_processors/project-coalescing
          target: .buildkite/run_gpu_benchmark.yml
          target_type: template
