steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - staticfloat/forerunner#0c78044b02ced95d8b9ca6fda7883fba45862fd2:
          # This will create one job per project
          watch:
            - path: benchmarks/.*\.jmd
            - path: benchmarks/.*\.toml
          path_processor: .buildkite/path_processors/project-coalescing
          target: .buildkite/run_benchmark.yml
          target_type: template
      - staticfloat/forerunner#0c78044b02ced95d8b9ca6fda7883fba45862fd2:
          # This will create one job overall, throwing all path information away
          watch:
            - path: src/*.*.jl
            - path: .*\\.toml
          target: .buildkite/test_sciml.yml
    agents:
      queue: "juliacpu"
      exclusive: true
