# This is a pipeline that rebuilds a model, then uploads the resultant
# model files and .PDF and other reports as (buildkite, not Julia) artifacts.

steps:
  - label: ":hammer: {PATH}"
      # Install Julia
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
    timeout_in_minutes: 60
    commands:
      # Rebuild the given model
      - echo "+++ Build {PATH}"
      - julia --project=. .buildkite/commands/rebuild_models.jl {PATH}
    artifact_paths:
       # Upload .html
      - "html/*.html"
      # Upload markdown
      - "markdown/*.md"
      # Upload notebook
      - "notebook/*.ipynb"
      # Upload .pdf files
      - "pdf/*.pdf"
      # Upload Julia script
      - "script/*.jl"