steps:
  - label: ":gear: Generate Dynamic Pipeline"
    command: |
      # Install required Julia packages
      julia -e 'using Pkg; Pkg.add("YAML")'
      
      # Generate dynamic pipeline based on changed files and queue configuration
      julia .buildkite/generate_pipeline.jl | buildkite-agent pipeline upload
    agents:
      queue: "juliaecosystem"
      arch: "x86_64"
      os: "linux"
