steps:
  - label: ":julia: Run tests on LTS"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.10
      - JuliaCI/julia-test#v1:
    timeout_in_minutes: 20
    artifact_paths:
       # Upload .html
      - "html/Testing/*.html"
      # Upload markdown
      - "markdown/Testing/*.md"
      # Upload notebook
      - "notebook/Testing/*.ipynb"
      # Upload .pdf files
      - "pdf/Testing/*.pdf"
      # Upload Julia script
      - "script/Testing/*.jl"
    agents:
      queue: "juliaecosystem"
      arch: "x86_64"
      os: "linux"
