#!/bin/bash

declare -A MODELS
for FILE in ${MODIFIED_FILES[@]}; do
    DIR="$(dirname "${FILE}")"
    # If we modify, e.g. `benchmarks/AdaptiveSDE/AdaptiveEfficiencyTests.jmd`, keep the `folder/jmdfile`
    # name until we hit `benchmark` or find a `Project.toml` file.
    while [[ "${DIR}" == benchmarks/* ]]; do
        if [[ -f "${DIR}/Project.toml" ]]; then
            # Strip `benchmarks` from the beginning to get the model name
            MODEL="${FILE#benchmarks/}"
            MODELS["${MODEL}"]=1

            echo "${FILE} triggered model '${MODEL}' rebuild"
            break
        fi
        DIR=$(dirname ${DIR})
    done
done

echo "${!MODELS[@]}"