[deps]
python = ">=3.12,<3.13"
numpy = ""
cuda-nvcc = ">=12,<13"

[pip.deps]
diffrax = ">=0.5"
equinox = ">=0.11"
jax = {version=">=0.4", extras=["cuda12"]}
torch = ">=2.0"
gradsolve = "@ git+https://github.com/ECLIPSE-AI4Science/gradsolve.git@3e11c1222640a028d60e15cfe6ab55e557bc4c11"
